version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    environment:
      - "QUERY_MAX_CLOCK_SKEW_ADJUSTMENT=60s"
    ports:
      - "14268:14268"   # jaeger-collector HTTP server (tracer provider)
      - "16686:16686"   # HTTP server (browser UI)
  user-management:
    container_name: user-management
    build:
      context: ""
      dockerfile: ./Dockerfile.user
    links:
      - jaeger
    environment:
      - "ANALYTICS_URL:http://analytics:8082/"
      - "OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces"
      - "OTEL_SERVICE_NAME=user-management"
    depends_on:
      - jaeger
    ports:
      - "8081:8081"
  analytics:
    container_name: analytics
    build:
      context: ""
      dockerfile: ./Dockerfile.analytics
    links:
      - jaeger
    environment:
      - "OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces"
      - "OTEL_SERVICE_NAME=analytics"
    depends_on:
      - jaeger
    ports:
      - "8082:8082"
  consumer:
    container_name: consumer
    build:
      context: ""
      dockerfile: ./Dockerfile.consumer
    links:
      - jaeger
    environment:
      - "OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces"
      - "URL=http://user-management:8081/users"
      - "OTEL_SERVICE_NAME=consumer"
    depends_on:
      - jaeger
      - user-management
    ports:
      - "8080:8080"